import type { Metadata } from "next";
import "./globals.css";
import ApplicationProvider from "@/components/ApplicationProvider";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ApplicationProvider>{children}</ApplicationProvider>
      </body>
    </html>
  );
}
